# This docker-compose file is used for development purposes.

services:
  cms:
    build:
      context: .
      args:
        # Send value of S3_BUCKET to the build process so that the correct import map is generated.
        S3_BUCKET: ${S3_BUCKET}
    environment:
      # The dockerized Payload runs in production, so its migrations won't work with the dev database. This overrides
      # the database URL given by the `.env` file.
      - DATABASE_URL=postgres://postgres:password@127.0.0.1:5432/payload_cms_v3_template_docker
    env_file:
      - .env
    network_mode: host
    volumes:
      - media:/app/media

volumes:
  media:
