# This docker-compose file is used for development purposes.

services:
  cms:
    build:
      context: .
    environment:
      # Override the database URL since the regular local db uses push mode and container will run in regular migration
      # mode.
      - DATABASE_URL=postgres://postgres:password@127.0.0.1:5432/payload_cms_v3_template
    env_file:
      - .env
    network_mode: host
    volumes:
      - media:/app/media

volumes:
  media:
